vscode:
  extensions:
    - dzannotti.vscode-babel-coloring@0.0.4:5Rlj2/kADFIl+crtoyiywQ==
    - dsznajder.es7-react-js-snippets@2.4.3:hx3eTJAy1EbZG5qQ6lxrdA==
    - ms-vscode.atom-keybindings@3.0.6:qhINEZXxQd8s8XbeWI17Jg==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:Jw3ra3MlKUzHrWQODXxjUw==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==
    - sldobri.bunker@1.1.6:Xa+1htqijOL82yvNL9QHPA==